Publisher.instance.name = 'Karoryfer Lecolds'
Publisher.instance.url = 'http://www.karoryfer.com'
public_dir = File.join(Rails.root, 'public')
Uploader::Release.store_dir = File.join(public_dir, 'downloads', 'wydawnictwa')
Uploader::TrackSource.store_dir = File.join(Rails.root, 'db', 'tracks')
Uploader::TrackPreview.store_dir = File.join(public_dir, 'downloads', 'tracks')
Uploader::ArtistImage.store_dir = File.join(public_dir, 'uploads', 'obrazki', 'artysci')
Uploader::AlbumImage.store_dir = File.join(public_dir, 'uploads', 'obrazki', 'wydawnictwa')
Uploader::EventImage.store_dir = File.join(public_dir, 'uploads', 'obrazki', 'wydarzenia')
Attachment::Uploader.store_dir = File.join(public_dir, 'uploads', 'attachments')
